resources:
- name: repo
  type: git
  source:
    uri: git@github.com:chaseoneillrnd/concourse-angular-demo.git
    branch: main
    private_key: |
      -----BEGIN OPENSSH PRIVATE KEY-----
      b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABCWEQT0wZ
      mt9IYJAXdrp4jjAAAAEAAAAAEAAAAzAAAAC3NzaC1lZDI1NTE5AAAAIPRB51BiIibf/29N
      lDfmTn8khd+lzLxwM7mo6dk3q/x3AAAAoNyfFnuOJunX1d6kFd/NixqHlJJMMAMHEeY9WT
      wMI0SpA/I0ZE+0vrOGVyA4G5ZMijR0gn9Z8vWU1h20NOIOlfz7xJIaAZr3mLQIN4hIUdIB
      +lp0rWVQSAyp2qCJXLnHcHNKZ9G+2ku1Q+AFFi1YRN4Rh/w7jS4a9EZ5RXI5FF2e+KlvsL
      jqkKLBsqIIAoSdFaDu+Jhm/gSCfVIPRCCRBM4=
      -----END OPENSSH PRIVATE KEY-----
    private_key_passphrase: Diamonds.1987
- name: node-image
  type: registry-image
  source:
    repository: trion/ng-cli-karma

jobs:
- name: angular-app-job
  plan:
  - in_parallel:
    - get: node-image
    - get: repo
      trigger: true
  - task: build-dependencies
    image: node-image
    config:
      inputs:
      - name: repo
      outputs:
      - name: dependencies
        path: repo/node_modules
      platform: linux
      run:
        path: sh
        args: 
        - -cx
        - | 
          npm i -g npm@latest
          npm i
        dir: repo
  - task: test
    image: node-image
    config:
      inputs:
      - name: repo
      - name: dependencies
        path: repo/node_modules
      platform: linux
      run:
        path: npm
        args: ["run", "test", "--", "--watch", "false"]
        dir: repo


